### ISSUE TITLE
只能下载前16首

### ISSUE THREAD

**Issue by Beadd** [Beadd/MusicDownloader#13]
你好大佬，感谢制作软件。
刚才先使用exe的软件，下载中程序停止运行，打开log文件只有前面音乐下载成功的信息，然后下载了.py文件运行。
[歌单链接](https://music.163.com/#/playlist?id=2944174721)
.exe和.py文件都只能下载前16首，.py报错信息为：
`17 Born a Stranger（slow）Traceback (most recent call last): `
`     File "E:\xxx\MusicDownloader.py", line 291, in <module>  `
`           if Music() == 0: `
`     File "E:\xxx\MusicDownloader.py", line 104, in Music `
`            plog(str(num) + ' ' + data['name'],str(num) + ' ' + data['name']) `
`     File "E:\xxx\MusicDownloader.py", line 53, in plog `
`            log.write(loginfo+"\n") `
`UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 7: illegal multibyte sequence`

_Originally posted by @jyldcr in https://github.com/Beadd/MusicDownloader/issues/7#issuecomment-1201967263_

**Comment by Beadd** [comment]
已经修复, 见v1.8.3
