### ISSUE TITLE
之前还能用的,今天突然报错

### ISSUE THREAD

**Issue by slam233** [Beadd/MusicDownloader#50]
```
1 Traceback (most recent call last):
  File "D:\mp3\new\musicdownloader_py\musicdownloader.py", line 891, in <module>
    main()
  File "D:\mp3\new\musicdownloader_py\musicdownloader.py", line 882, in main
    if args.args_url is None: pure_main()
  File "D:\mp3\new\musicdownloader_py\musicdownloader.py", line 865, in pure_mai
n
    while True: start_function()
  File "D:\mp3\new\musicdownloader_py\musicdownloader.py", line 818, in start_fu
nction
    mode_music(api_path, g_header, g_proxies, g_header163)
  File "D:\mp3\new\musicdownloader_py\musicdownloader.py", line 666, in mode_mus
ic
    music_path = json_download_music(data, headers, proxies)
  File "D:\mp3\new\musicdownloader_py\musicdownloader.py", line 225, in json_dow
nload_music
    name = json_get_music_name(data)
  File "D:\mp3\new\musicdownloader_py\musicdownloader.py", line 100, in json_get
_music_name
    name = data['name']
TypeError: string indices must be integers

```
咋回事啊

**Comment by slam233** [comment]
超出每日api调用上限了XD
