### ISSUE TITLE
自建API，有cookie，win能使用，macOS蒙特雷个别歌曲保存不了

### ISSUE THREAD

**Issue by ptxbc** [Beadd/MusicDownloader#54]
请输入歌曲或歌单或歌手或专辑链接：https://music.163.com/song?id=515796411
1 金玟岐 - 手机
Traceback (most recent call last):
  File "/Users/xbc/Documents/musicdownloader/musicdownloader.py", line 891, in <module>
    main()
  File "/Users/xbc/Documents/musicdownloader/musicdownloader.py", line 882, in main
    if args.args_url is None: pure_main()
  File "/Users/xbc/Documents/musicdownloader/musicdownloader.py", line 865, in pure_main
    while True: start_function()
  File "/Users/xbc/Documents/musicdownloader/musicdownloader.py", line 813, in start_function
    mode_music(api_path, g_header, g_proxies, g_header163)
  File "/Users/xbc/Documents/musicdownloader/musicdownloader.py", line 666, in mode_music
    music_path = json_download_music(data, headers, proxies)
  File "/Users/xbc/Documents/musicdownloader/musicdownloader.py", line 245, in json_download_music
    with open(music_path, "wb") as code:
FileNotFoundError: [Errno 2] No such file or directory: 'MusicB/金玟岐 - 手机.net/20230715160620/70bf5015034f9363dfa9f5137cc19df6/ymusic/TDQrAj_iWFpRpdWfuAJIuA==/509951162896830193'

有些歌曲能保存，有些保存不了。https://music.163.com/song?id=1315568574   比如这首歌就能保存。win10系统下用打包好的exe没这个问题。

系统：X86平台 macOS 蒙特雷

**Comment by Beadd** [comment]
https://music.163.com/song?id=515796411，https://music.163.com/#/song?id=1315568574测试这两首歌曲下载都没问题，你可以访问https://{你的API服务器}/meting/?type=song&id=515796411来测试是否解析成功。如果你用的是默认的API，则可能是今天访问次数太多了

**Comment by ptxbc** [comment]
解析不成功，提示这个：
[{"name":"\u624b\u673a","artist":"\u91d1\u739f\u5c90","url":"http:\/\/192.168.10.3\/?server=netease&type=url&id=515796411","pic":"http:\/\/192.168.10.3\/?server=netease&type=pic&id=109951163064544587","lrc":"http:\/\/192.168.10.3\/?server=netease&type=lrc&id=515796411"}]

**Comment by Beadd** [comment]
默认API可解析，你可以将API换回默认试试
